apiVersion: apps/v1
kind: Deployment
metadata:
  name: alemavintage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alemavintage
  template:
    metadata:
      labels:
        app: alemavintage
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: alemavintage
        image: cerit.io/roman_alexander_mariancik/alemavintage-image
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/src/alemavintage/media
          name: alemavintage-media
        env:
        - name: PUBLIC_DOMAIN
          value: "https://alemavintage.dyn.cloud.e-infra.cz/"
        - name: USE_SECURE_COOKIE
          value: "true"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: RUST_LOG
          value: "debug"
        - name: TMPDIR
          value: "./media"
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "3"
      volumes:
      - name: alemavintage-media
        persistentVolumeClaim:
          claimName: alemavintage-pvc